name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # Allows manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install DVC
        run: |
          python -m pip install --upgrade pip
          pip install dvc[s3] python-dotenv 
      - name: Pull from DVC
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user $DAGSHUB_USERNAME
          dvc remote modify origin --local password $DAGSHUB_TOKEN
          dvc pull
     

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.loan }}
        run: |
          # 1. Configure git user
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 2. Clean the git history in the runner environment
          rm -rf .git
          
          # 3. Create a fresh repository with only current files
          git init
          git checkout -b main
          git add .
          git commit -m "Deploy current state to Hugging Face"
          
          # 4. Push this clean commit
          git push --force https://oauth:$HF_TOKEN@huggingface.co/spaces/MDFayaz/loan_approval_prediction main
